// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nurbnb.Hospedaje.Infrastructure.EF.Contexts;

#nullable disable

namespace Nurbnb.Hospedaje.Infrastructure.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20240127025842_initialstructure")]
    partial class initialstructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nurbnb.Hospedaje.Infrastructure.EF.ReadModel.CheckinReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("checkinId");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("hora");

                    b.Property<string>("Instrucciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("instrucciones");

                    b.Property<Guid>("OperacionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("operacionId");

                    b.HasKey("Id");

                    b.ToTable("checkin");
                });

            modelBuilder.Entity("Nurbnb.Hospedaje.Infrastructure.EF.ReadModel.CheckoutReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("checkoutId");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("hora");

                    b.Property<Guid>("OperacionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("operacionId");

                    b.HasKey("Id");

                    b.ToTable("checkout");
                });
#pragma warning restore 612, 618
        }
    }
}
